import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, View } from 'react-native';
import { useStore } from '@/src/store';
import { api } from '@/src/api';
import { dayjs, dateInput, parseDate } from '@/src/dates';
import { makeStyles, useTheme } from '@/src/theme';
import { Shell, go } from '@/src/components/Shell';
import { Button, Card, Chips, Empty, ErrorMessage, Icon, IconButton, Input, Label, Sheet } from '@/src/components/ui';
import { EditorForm } from '@/src/components/Form';

const types = [{ label: 'All', value: 'all' }, { label: 'Events', value: 'events' }, { label: 'Homework', value: 'homework' }, { label: 'Tests', value: 'tests' }, { label: 'Reminders', value: 'reminders' }, { label: 'Renewals', value: 'subscriptions' }];
export default function Calendar() {
  const { data, user } = useStore(), s = useStyles(), { colors } = useTheme();
  const [selected, setSelected] = useState(data?.today || dayjs().tz(user.timezone).format('YYYY-MM-DD')), [mode, setMode] = useState('Month'), [type, setType] = useState('all'), [items, setItems] = useState<any[]>([]), [completedRequest, setCompletedRequest] = useState<{ start: string; end: string; data: unknown } | null>(null), [error, setError] = useState(''), [seed, setSeed] = useState<any>(null), [picker, setPicker] = useState(false), [jump, setJump] = useState(dateInput(selected));
  const date = dayjs(selected), monday = date.subtract((date.day() + 6) % 7, 'day'), start = mode === 'Month' ? date.startOf('month').format('YYYY-MM-DD') : monday.format('YYYY-MM-DD'), end = mode === 'Month' ? date.endOf('month').format('YYYY-MM-DD') : monday.add(6, 'day').format('YYYY-MM-DD');
  const busy = completedRequest?.start !== start || completedRequest?.end !== end || completedRequest?.data !== data;
  useEffect(() => { let live = true; api(`/calendar?start=${start}&end=${end}`).then(v => { if (live) { setItems(v); setError(''); } }).catch(e => live && setError(e.message)).finally(() => live && setCompletedRequest({ start, end, data })); return () => { live = false; }; }, [start, end, data]);
  const shown = items.filter(i => (type === 'all' || i.kind === type) && (mode === 'Month' || i.date === selected));
  const changePeriod = (direction: number) => setSelected(date.add(direction, mode === 'Month' ? 'month' : 'week').format('YYYY-MM-DD'));
  const offset = (date.startOf('month').day() + 6) % 7, cells = Array.from({ length: Math.ceil((offset + date.daysInMonth()) / 7) * 7 }, (_, i) => i - offset + 1);
  return <Shell title="Calendar" section="calendar" right={<IconButton name="add" testID="calendar-add" label="Add event" onPress={() => setSeed({ date: selected })} />} chrome={<>
    <View style={s.navigation}><IconButton name="chevron-back" testID="calendar-previous" label="Previous period" onPress={() => changePeriod(-1)} /><Pressable testID="calendar-period" onPress={() => { setJump(dateInput(selected)); setPicker(true); }}><Label size={19} weight="600">{date.format('MMMM YYYY')}</Label></Pressable><IconButton name="chevron-forward" testID="calendar-next" label="Next period" onPress={() => changePeriod(1)} /></View>
    <View style={s.mode}><View style={s.segment}>{['Week', 'Month'].map(m => <Pressable key={m} testID={`calendar-mode-${m.toLowerCase()}`} onPress={() => setMode(m)} style={[s.segmentButton, m === mode && s.segmentActive]}><Label size={13} weight="500">{m}</Label></Pressable>)}</View><Button title="Today" testID="calendar-today" variant="ghost" onPress={() => setSelected(data?.today || dayjs().tz(user.timezone).format('YYYY-MM-DD'))} /></View>
    <Chips options={types} value={type} onChange={setType} testID="calendar-type" />
    {mode === 'Week' && <Chips options={Array.from({ length: 7 }, (_, i) => ({ label: monday.add(i, 'day').format('ddd D'), value: monday.add(i, 'day').format('YYYY-MM-DD') }))} value={selected} onChange={setSelected} testID="calendar-day" />}
  </>}>
    <ScrollView contentContainerStyle={s.content} testID="calendar-scroll">
      {!!error && <ErrorMessage message={error} />}{busy && <ActivityIndicator color={colors.brandPrimary} />}
      {mode === 'Month' && <Card style={{ padding: 12 }}><View style={s.weekdays}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => <View key={i} style={s.cell}><Label size={11} muted>{d}</Label></View>)}</View><View style={s.grid}>{cells.map((d, i) => { const valid = d > 0 && d <= date.daysInMonth(), iso = date.date(d).format('YYYY-MM-DD'), count = items.filter(x => x.date === iso && (type === 'all' || x.kind === type)).length; return <Pressable key={i} disabled={!valid} testID={valid ? `calendar-date-${iso}` : `calendar-blank-${i}`} onPress={() => { setSelected(iso); setSeed({ date: iso }); }} style={[s.cell, s.day, valid && iso === data?.today && s.today, valid && iso === selected && s.selected]}>{valid && <><Label size={15} weight={iso === data?.today ? '700' : '400'}>{d}</Label><View style={[s.dot, { backgroundColor: count ? colors.brandPrimary : colors.transparent }]} /></>}</Pressable>; })}</View><Label size={11} muted style={{ padding: 8 }}>Tap a day to add an event.</Label></Card>}
      {shown.length > 0 && <View style={{ gap: 12 }}><Label weight="600">{mode === 'Month' ? 'This month' : date.format('dddd, D MMMM')}</Label>{shown.map(item => <Pressable testID={`calendar-item-${item.id}`} key={item.id} onPress={() => go(item.kind, { item: item.source_id })}><Card style={s.event}><View style={s.dateBadge}><Label size={10} muted>{dayjs(item.date).format('MMM')}</Label><Label size={21} weight="600">{dayjs(item.date).format('DD')}</Label></View><View style={{ flex: 1, gap: 4 }}><Label weight="600" size={14}>{item.title}</Label><Label muted size={12}>{item.kind === 'subscriptions' ? 'Renewal' : item.kind[0].toUpperCase() + item.kind.slice(1)} · {item.time || (item.all_day ? 'All day' : 'Date only')}{item.status ? ` · ${item.status}` : ''}</Label></View><Icon name="chevron-forward" size={15} /></Card></Pressable>)}</View>}
      {mode === 'Month' && !busy && !shown.length && <Empty title="A clear calendar" detail="Tap any day to plan something new." icon="calendar-outline" />}
      {mode === 'Week' && <View><Label size={13} muted style={{ marginBottom: 12 }}>Tap a time to add an event.</Label>{Array.from({ length: 24 }, (_, i) => <Pressable key={i} testID={`calendar-hour-${i}`} onPress={() => setSeed({ date: selected, time: `${String(i).padStart(2, '0')}:00`, end_time: i === 23 ? '23:59' : `${String(i + 1).padStart(2, '0')}:00` })} style={s.hour}><Label size={12} muted style={{ width: 48 }}>{String(i).padStart(2, '0')}:00</Label><View style={s.hourLine} /><Icon name="add" size={15} color={colors.muted} /></Pressable>)}</View>}
    </ScrollView>
    {seed && <EditorForm kind="events" seed={seed} onClose={() => setSeed(null)} />}
    <Sheet visible={picker} title="Go to date" onClose={() => setPicker(false)}><Input label="Date · DD/MM/YYYY" testID="calendar-jump-date" value={jump} onChangeText={setJump} /><Button title="Go to date" testID="calendar-jump-apply" onPress={() => { try { setSelected(parseDate(jump)); setPicker(false); } catch (e: any) { setError(e.message); } }} /></Sheet>
  </Shell>;
}
const useStyles = makeStyles(c => ({ content: { padding: 20, paddingBottom: 32, gap: 20, maxWidth: 760, width: '100%', alignSelf: 'center' }, navigation: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14 }, mode: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20, alignItems: 'center', marginTop: 8 }, segment: { flexDirection: 'row', padding: 3, backgroundColor: c.surfaceTertiary, borderRadius: 12 }, segmentButton: { minWidth: 75, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: c.surfaceSecondary }, weekdays: { flexDirection: 'row' }, grid: { flexDirection: 'row', flexWrap: 'wrap' }, cell: { width: '14.285714%', alignItems: 'center', justifyContent: 'center', minHeight: 36 }, day: { minHeight: 48, gap: 4, borderRadius: 12 }, today: { backgroundColor: c.brandTertiary }, selected: { borderWidth: 1, borderColor: c.brandPrimary }, dot: { width: 4, height: 4, borderRadius: 2 }, event: { flexDirection: 'row', alignItems: 'center', gap: 15, padding: 15 }, dateBadge: { backgroundColor: c.surfaceTertiary, borderRadius: 11, padding: 8, minWidth: 48, alignItems: 'center' }, hour: { flexDirection: 'row', alignItems: 'center', gap: 12, height: 64 }, hourLine: { height: 1, backgroundColor: c.border, flex: 1 } }));
