import React, { useRef, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, View } from 'react-native';
import { router } from 'expo-router';
import { useStore } from '@/src/store';
import { makeStyles, useTheme } from '@/src/theme';
import { dayjs, money } from '@/src/dates';
import { Shell, go } from '@/src/components/Shell';
import { Button, Card, ErrorMessage, Icon, IconButton, Label, Sheet } from '@/src/components/ui';
import { EditorForm } from '@/src/components/Form';
import { HomeClock } from '@/src/components/HomeClock';
import { useHomeTime } from '@/src/hooks/useHomeTime';
import { useReducedMotion } from '@/src/hooks/useReducedMotion';

export default function Home() {
  const { user, data, records, refresh, loading, error } = useStore(), s = useStyles(), { colors } = useTheme();
  const [carousel, setCarousel] = useState(0), [width, setWidth] = useState(340), [quick, setQuick] = useState(false), [create, setCreate] = useState('');
  const scroll = useRef<ScrollView>(null);
  const now = useHomeTime(user.timezone), greeting = now.greeting, reduceMotion = useReducedMotion();
  const day = now.dateKey, upcoming = (data?.upcoming || []).filter((r: any) => !['Done', 'Completed'].includes(r.status)), notifications = (data?.notifications || []).filter((n: any) => !n.read);
  const agenda = upcoming.filter((r: any) => r.date === day), homework = records('homework').filter((r: any) => r.status === 'To do').sort((a: any, b: any) => a.date.localeCompare(b.date)), tests = records('tests').filter((r: any) => r.status === 'Scheduled' && r.date >= day).sort((a: any, b: any) => a.date.localeCompare(b.date));
  const recap = data?.recap, weekday = now.weekday, lessons = records('timetable').filter((r: any) => r.day === weekday).sort((a: any, b: any) => a.hour - b.hour);
  const openRecord = (item: any) => item.kind === 'notes' ? router.push(`/note/${item.id}` as any) : go(item.kind, { item: item.source_id || item.id });
  function sectionCard(title: string, icon: string, key: string, items: any[], empty: string) {
    return <Card testID={`home-${key}-card`}><View style={s.cardHead}><Icon name={icon} size={19} color={colors.brandPrimary} /><Label size={16} weight="600" style={{ flex: 1 }}>{title}</Label><IconButton name="arrow-forward" label={`View all ${title}`} testID={`home-${key}-all`} onPress={() => go(key)} /></View>
      {items.length ? items.slice(0, 2).map((item: any) => <Pressable testID={`home-item-${item.id}`} key={item.id} onPress={() => openRecord(item)} style={s.item}><View style={[s.itemDot, { backgroundColor: item.color || colors.brandPrimary }]} /><View style={{ flex: 1 }}><Label size={14} weight="500">{item.title || item.name}</Label><Label size={12} muted>{item.date ? dayjs(item.date).format('ddd, D MMM') + (item.time ? ` · ${item.time}` : '') : 'Tap to keep writing'}</Label></View></Pressable>) : <Label muted size={14} style={s.emptyText}>{empty}</Label>}
      <Pressable testID={`home-${key}-view-all`} accessibilityRole="button" onPress={() => go(key)}><Label size={12} weight="600" style={{ color: colors.brandPrimary }}>View all</Label></Pressable>
    </Card>;
  }
  return <Shell section="" right={<IconButton name="add-outline" testID="home-quick-add" label="Quick add" onPress={() => setQuick(true)} />}>
    <ScrollView testID="home-scroll" refreshControl={<RefreshControl refreshing={loading && !!data} onRefresh={() => refresh().catch(() => {})} tintColor={colors.brandPrimary} />} contentContainerStyle={s.content}>
      <View style={s.greeting}><Label size={11} weight="600" muted style={s.eyebrow}>A LITTLE MORE CLARITY, EVERY DAY</Label><Label testID="home-greeting" size={28} weight="600" style={{ letterSpacing: -0.8 }}>{greeting},{'\n'}{user.name}<Label size={28} style={{ color: colors.brandPrimary }}>.</Label></Label><Label size={14} muted>Your day, all in one place.</Label></View>
      {!!error && <ErrorMessage message={error} retry={() => refresh().catch(() => {})} />}
      <HomeClock zone={user.timezone} styles={s} />
      <View onLayout={e => setWidth(e.nativeEvent.layout.width)}><ScrollView ref={scroll} horizontal pagingEnabled showsHorizontalScrollIndicator={false} onMomentumScrollEnd={e => setCarousel(Math.round(e.nativeEvent.contentOffset.x / width))} testID="home-carousel">
        {[{ title: 'Notifications', icon: 'notifications-outline', key: 'notifications', items: notifications, empty: 'You’re all caught up.', detail: 'Your reminders will appear here.' }, { title: 'Upcoming Events', icon: 'calendar-outline', key: 'calendar', items: upcoming, empty: 'A little room to breathe.', detail: 'Add an event to plan what’s next.' }].map(card => <View key={card.key} style={{ width }}><Pressable testID={`carousel-${card.key}`} onPress={() => go(card.key)} style={({ pressed }) => [s.carouselCard, { opacity: pressed ? 0.8 : 1 }]}><View style={s.cardHead}><View style={s.carouselIcon}><Icon name={card.icon} size={20} color={colors.brandPrimary} /></View><Label size={15} weight="600" style={{ flex: 1 }}>{card.title}</Label><Label testID={`${card.key}-count`} size={12} weight="600" style={s.count}>{card.items.length}</Label><Icon name="arrow-up-outline" size={16} color={colors.brandPrimary} /></View>{card.items.length ? <View><Label weight="500" size={16}>{card.items[0].title}</Label><Label muted size={12}>{card.items.length > 1 ? `+${card.items.length - 1} more to explore` : 'Tap to view details'}</Label></View> : <View><Label weight="500" size={16}>{card.empty}</Label><Label muted size={12} style={{ marginTop: 3 }}>{card.detail}</Label></View>}</Pressable></View>)}
      </ScrollView><View style={s.carouselControls}><IconButton name="chevron-back" testID="carousel-previous" label="Previous card" onPress={() => { setCarousel(0); scroll.current?.scrollTo({ x: 0, animated: !reduceMotion }); }} /><View style={s.dots}>{[0, 1].map(index => <View key={index} style={[s.dot, { backgroundColor: carousel === index ? colors.brandPrimary : colors.borderStrong, width: carousel === index ? 18 : 5 }]} />)}</View><IconButton name="chevron-forward" testID="carousel-next" label="Next card" onPress={() => { setCarousel(1); scroll.current?.scrollTo({ x: width, animated: !reduceMotion }); }} /></View></View>
      {!data && loading ? <ActivityIndicator color={colors.brandPrimary} /> : data && <>
        <View style={s.sectionHeading}><Label size={20} weight="600">A look at your day</Label><Label size={11} muted>{now.shortDate}</Label></View>
        {sectionCard("Today’s Agenda", 'calendar-clear-outline', 'calendar', agenda, 'No plans for today. Make space for what matters.')}
        {lessons.length > 0 && <Card><Label weight="600">Today’s lessons</Label>{lessons.map((slot: any) => <Pressable testID={`lesson-${slot.id}`} key={slot.id} onPress={() => go('timetable')} style={s.recapRow}><Label size={13} muted>{String(slot.hour).padStart(2, '0')}:00</Label><Label size={14}>{records('subjects').find((r: any) => r.id === slot.subject_id)?.name}</Label></Pressable>)}</Card>}
        {sectionCard('Homework Due Soon', 'checkbox-outline', 'homework', homework, 'Nothing due. Your next assignment starts here.')}
        {sectionCard('Upcoming Tests', 'reader-outline', 'tests', tests, 'No tests scheduled.')}
        {sectionCard('Recent Notes', 'document-text-outline', 'notes', records('notes'), 'A fresh page for your next thought.')}
        <View style={s.twoColumns}><Pressable testID="home-finance-all" onPress={() => go('finance')} style={s.halfCard}><Icon name="wallet-outline" size={21} color={colors.brandPrimary} /><Label size={13} weight="600">Finance Overview</Label><Label size={22} weight="600" testID="home-current-balance">{money(data.finance.current)}</Label><Label muted size={11}>Current balance · EUR</Label><Label size={12} style={{ color: colors.brandPrimary }}>View all →</Label></Pressable><Pressable testID="home-trading-all" onPress={() => go('pnl')} style={s.halfCard}><Icon name="trending-up-outline" size={21} color={colors.brandPrimary} /><Label size={13} weight="600">Trading Snapshot</Label><Label size={22} weight="600">{records('trades').filter((t: any) => t.status === 'Closed').length || '—'}</Label><Label muted size={11}>{records('trades').length ? 'Closed trades' : 'No trades yet'}</Label><Label size={12} style={{ color: colors.brandPrimary }}>View all →</Label></Pressable></View>
        <Card testID="daily-recap" style={s.recap}><View style={s.cardHead}><Icon name="sparkles-outline" size={19} color={colors.brandPrimary} /><Label size={18} weight="600">Quick Daily Recap</Label></View><Label muted size={12}>Today, from your actual activity.</Label>{[["Today’s commitments", `${recap.events}`], ['Homework completed today', `${recap.homework_completed}`], ['Homework still to submit', `${recap.homework_pending}`], ['Tests in the next 7 days', `${recap.tests}`], ['Notes edited today', `${recap.notes}`], ['Grades recorded today', `${recap.grades}`]].map(([label, value]) => <View style={s.recapRow} key={label}><Label size={13} muted>{label}</Label><Label weight="600" size={13}>{value}</Label></View>)}<View style={s.rule} /><Label size={13}>{recap.closed_trades ? `${recap.closed_trades} trades closed today` : 'No trades closed today'}</Label>{Object.entries(recap.pnl).map(([currency, amount]) => <Label key={currency} size={13}>{money(amount as number, currency)}</Label>)}<View style={s.recapRow}><Label size={13} muted>Money recorded today</Label><Label size={12}>+{money(recap.income)} / −{money(recap.expense)}</Label></View><Label size={13} muted>{upcoming.find((r: any) => r.kind === 'subscriptions') ? `Next renewal: ${upcoming.find((r: any) => r.kind === 'subscriptions').title}` : 'No upcoming renewals'}</Label></Card>
        <Label muted size={11} style={s.endNote}>Your space. Your pace.</Label>
      </>}
    </ScrollView>
    <Sheet visible={quick} title="Add to your day" onClose={() => setQuick(false)}>{[['events', 'Event', 'calendar-outline'], ['notes', 'Note', 'document-text-outline'], ['reminders', 'Reminder', 'notifications-outline'], ['homework', 'Homework', 'checkbox-outline'], ['finance', 'Transaction', 'wallet-outline'], ['trades', 'Trade', 'swap-horizontal-outline']].map(([key, title, icon]) => <Button key={key} title={title} icon={icon} variant="ghost" testID={`quick-add-${key}`} onPress={() => { setQuick(false); setCreate(key); }} style={{ justifyContent: 'flex-start', marginBottom: 8 }} />)}</Sheet>
    {!!create && <EditorForm key={create} kind={create} onClose={() => setCreate('')} onSaved={(r: any) => { if (create === 'notes') router.push(`/note/${r.id}` as any); }} />}
  </Shell>;
}
const useStyles = makeStyles(c => ({ content: { padding: 20, paddingTop: 25, paddingBottom: 32, gap: 16, width: '100%', maxWidth: 760, alignSelf: 'center' }, greeting: { gap: 8, marginBottom: 10 }, eyebrow: { letterSpacing: 1.4 }, clockCard: { padding: 18, gap: 12 }, cardHead: { flexDirection: 'row', alignItems: 'center', gap: 8 }, clockRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, dayTile: { borderRadius: 14, width: 60, height: 68, backgroundColor: c.brandTertiary, justifyContent: 'center', alignItems: 'center' }, carouselCard: { borderRadius: 20, backgroundColor: c.brandSecondary, padding: 20, minHeight: 156, gap: 20 }, carouselIcon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: c.surfaceSecondary }, count: { minWidth: 23, textAlign: 'center', color: c.brandPrimary }, carouselControls: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', height: 30, marginTop: 6 }, dots: { flexDirection: 'row', gap: 5, alignItems: 'center' }, dot: { height: 5, borderRadius: 3 }, sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6, marginBottom: 0 }, item: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 48 }, itemDot: { width: 5, height: 28, borderRadius: 3 }, emptyText: { lineHeight: 22, paddingVertical: 4 }, twoColumns: { flexDirection: 'row', gap: 12 }, halfCard: { flex: 1, backgroundColor: c.surfaceSecondary, borderRadius: 18, borderWidth: 1, borderColor: c.border, padding: 16, gap: 9 }, recap: { backgroundColor: c.brandTertiary, marginTop: 8, gap: 13 }, recapRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, rule: { height: 1, backgroundColor: c.border, marginVertical: 4 }, endNote: { textAlign: 'center', paddingTop: 10, letterSpacing: 0.5 } }));