import React, { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useStore } from '@/src/store';
import { dayjs } from '@/src/dates';
import { makeStyles, useTheme } from '@/src/theme';
import { Shell } from '@/src/components/Shell';
import { Button, Card, Chips, Confirm, Empty, ErrorMessage, Icon, IconButton, Input, Label, Sheet } from '@/src/components/ui';
import { EditorForm } from '@/src/components/Form';

export default function Notes() {
  const params = useLocalSearchParams(), { records, user, mutate, refresh, data, loading } = useStore(), s = useStyles(), { colors } = useTheme();
  const [folder, setFolder] = useState(String(params.folder || 'all')), [search, setSearch] = useState(''), [creating, setCreating] = useState(false), [selecting, setSelecting] = useState(false), [selected, setSelected] = useState<string[]>([]), [move, setMove] = useState(false), [deleting, setDeleting] = useState<any>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const notes = records('notes').filter((n: any) => (folder === 'all' || (folder === 'unfiled' ? !n.folder_id : n.folder_id === folder)) && n.title.toLowerCase().includes(search.toLowerCase())).sort((a: any, b: any) => b.updated_at.localeCompare(a.updated_at));
  function select(id: string) { setSelected(ids => ids.includes(id) ? ids.filter(v => v !== id) : [...ids, id]); }
  async function moveTo(folder_id: string | null) { setBusy(true); setError(''); try { await mutate('/notes/move', 'POST', { ids: selected, folder_id }); setMove(false); setSelected([]); setSelecting(false); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  async function remove() { setBusy(true); try { await mutate('/records/notes/' + deleting.id, 'DELETE', { version: deleting.version }); setDeleting(null); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  return <Shell title="Notes" section="notes" right={<IconButton name="add" testID="add-notes" label="New note" onPress={() => setCreating(true)} />} chrome={<><View style={s.search}><Input label="" testID="notes-search" placeholder="Search your notebooks" value={search} onChangeText={setSearch} /></View><Chips options={[{ label: 'All notes', value: 'all' }, { label: 'Unfiled', value: 'unfiled' }, ...records('folders').map((f: any) => ({ label: f.name, value: f.id }))]} value={folder} onChange={setFolder} testID="notes-folder" /><View style={s.listHeader}><Label size={12} muted>{notes.length} notebooks · Last modified</Label><Button title={selecting ? 'Cancel' : 'Select'} testID="notes-select-mode" variant="ghost" onPress={() => { setSelecting(!selecting); setSelected([]); }} /></View></>}>
    <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading && !!data} onRefresh={() => refresh().catch(() => {})} />}>
      {!notes.length ? <Empty title="Room for every thought" detail="Type, draw and connect your ideas on the same page." icon="document-text-outline" action={() => setCreating(true)} actionLabel="Create a notebook" /> : notes.map((note: any) => <Pressable testID={`note-card-${note.id}`} key={note.id} onPress={() => selecting ? select(note.id) : router.push(`/note/${note.id}` as any)}><Card style={s.noteCard}><View style={s.preview}><Icon name={selecting ? selected.includes(note.id) ? 'checkmark-circle' : 'ellipse-outline' : 'document-text-outline'} size={29} color={colors.brandPrimary} /></View><View style={{ flex: 1, gap: 6 }}><Label size={17} weight="600">{note.title}</Label><Label size={12} muted>{records('subjects').find((r: any) => r.id === note.subject_id)?.name || 'Personal notes'}</Label><Label size={11} muted>Edited {dayjs(note.updated_at).tz(user.timezone).format('D MMM · HH:mm')}</Label></View>{!selecting && <IconButton name="trash-outline" testID={`note-delete-${note.id}`} label="Delete notebook" onPress={() => { setDeleting(note); setError(''); }} />}</Card></Pressable>)}
      {!!error && !deleting && !move && <ErrorMessage message={error} />}
    </ScrollView>
    {selecting && <View style={s.selectionFooter}><Button title={`Move ${selected.length} ${selected.length === 1 ? 'note' : 'notes'}`} testID="notes-move" icon="folder-outline" disabled={!selected.length} onPress={() => setMove(true)} /></View>}
    {creating && <EditorForm kind="notes" seed={folder !== 'all' && folder !== 'unfiled' ? { folder_id: folder } : {}} onClose={() => setCreating(false)} onSaved={(r: any) => router.push(`/note/${r.id}` as any)} />}
    <Sheet visible={move} title="Move selected notes" onClose={() => setMove(false)}><Button title="Unfiled" testID="move-unfiled" variant="ghost" onPress={() => moveTo(null)} busy={busy} />{records('folders').map((f: any) => <Button key={f.id} title={f.name} testID={`move-folder-${f.id}`} variant="ghost" onPress={() => moveTo(f.id)} busy={busy} />)}{!!error && <ErrorMessage message={error} />}</Sheet>
    <Confirm visible={!!deleting} title="Delete this notebook?" message="All pages in this notebook will be deleted. This cannot be undone." onCancel={() => setDeleting(null)} onConfirm={remove} busy={busy} error={error} />
  </Shell>;
}
const useStyles = makeStyles(c => ({ search: { paddingHorizontal: 20, height: 66, overflow: 'hidden' }, listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20 }, content: { padding: 20, paddingTop: 8, paddingBottom: 32, gap: 14, maxWidth: 760, width: '100%', alignSelf: 'center' }, noteCard: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 14 }, preview: { width: 58, height: 76, borderRadius: 9, backgroundColor: c.brandTertiary, borderWidth: 1, borderColor: c.border, alignItems: 'center', justifyContent: 'center' }, selectionFooter: { paddingHorizontal: 20, paddingVertical: 14, borderTopWidth: 1, borderTopColor: c.border, backgroundColor: c.surfaceSecondary } }));